name: Build and Publish Release AAR

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '*/'
    push:
      tags-ignore:
        - '*'
    message:
      - '/^v\d+\.\d+\.\d+$/'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Get Library Version
      id: get_version
      run: echo "::set-output name=library_version::$(./gradlew TestUtils:printLibraryVersion --quiet)"

    - name: Generate Library AAR
      run: ./gradlew TestUtils:assembleRelease

    - name: Create pre-release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.ATOKEN }}"
        automatic_release_tag: ${{ steps.get_version.outputs.library_version }}
        prerelease: true
        title: "v¬${{ steps.get_version.outputs.library_version }}"
        files: |
          app/build/outputs/aar/*.aar
