name: Build and Publish Release AAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Get Library Version
        id: get_version
        run: echo "::set-output name=library_version::$(grep -oP "libraryVersion = '\K[0-9.]+" build.gradle)"

      - name: Build AAR
        run: ./gradlew assembleRelease

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.library_version }}
          release_name: Release v${{ steps.get_version.outputs.library_version }}
          draft: false
          prerelease: false

      - name: Upload AAR
        id: upload_aar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path/to/your/aar/file.aar
          asset_name: your-aar-file.aar
          asset_content_type: application/octet-stream
